Ticket_App/Models/EmailSender.cs
using System.Net.Mail;
using System.Net;
using Ticket_App.Interfaces;

namespace Ticket_App.Models
{
    public class EmailSender : IEmailSender
    {
        public Task SendEmailAsync(string email, string subject, string message)
        {
            var mail = "";
            var pw = "";

            var client = new SmtpClient("", 587)
            {
                EnableSsl = true,
                Credentials = new NetworkCredential(mail, pw)
            };

            return client.SendMailAsync(
                new MailMessage(from: mail,
                                to: email,
                                subject,
                                message));
        }
    }
}

Ticket_App/Models/Employee.cs
namespace Ticket_App.Models
{
    public class Employee
    {
        public int EmployeeId { get; set; }
        public string CardNumber { get; set; }
        public string EmployeeName { get; set; }
    }
}

Ticket_App/Models/Ticket.cs
using System.Diagnostics.CodeAnalysis;

namespace Ticket_App.Models
{
    public class Ticket
    {
        public int TicketID { get; set; }
        [AllowNull] public string CardNumber { get; set; }
        [AllowNull] public string EmployeeName { get; set; }
        [AllowNull] public string Subject { get; set; }
        public DateTime CreatedAT { get; set; }
    }
}

Ticket_App/Models/TicketTopic.cs
namespace Ticket_App.Models
{
    public class TicketTopic
    {
        public TicketTopic(int ticketTopicID, string ticketTopicName, string imageName)
        {
            TicketTopicID = ticketTopicID;
            TicketTopicName = ticketTopicName;
            ImageName = imageName;
        }

        public int TicketTopicID { get; set; }
        public string TicketTopicName { get; set; }
        public string ImageName { get; set; }

    }
}

Ticket_App/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ticket_App.Data;
using Ticket_App.Models;
using Ticket_App.Interfaces;
using Microsoft.CodeAnalysis.Elfie.Serialization;

namespace Ticket_App.Pages.Shared.Tickets
{
    public class CreateModel : PageModel
    {
        private readonly Ticket_App.Data.ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;

        public string Name { get; set; }
        public string CardNumber { get; set; }
        public List<TicketTopic> Topics = new List<TicketTopic>();

        public CreateModel(Ticket_App.Data.ApplicationDbContext context, IEmailSender emailSender)
        {
            _context = context;
            this._emailSender = emailSender;
        }

        public IActionResult OnGet(string cardNumber)
        {
            var employeeName = _context.Employee
                .Where (a => a.CardNumber == cardNumber)
                .Select(b => b.EmployeeName)
                .FirstOrDefault();

            Name = employeeName;
            CardNumber = cardNumber;

            foreach(var topic in _context.TicketTopic)
            {
                Topics.Add(new TicketTopic(topic.TicketTopicID, topic.TicketTopicName, topic.ImageName));
            }
            

            foreach(var topic in Topics)
            {
                Console.WriteLine(topic.TicketTopicID + " " + topic.TicketTopicName);
            }


            return Page();
        }

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(string cardNumber)
        {
            var employeeName = _context.Employee
                .Where(a => a.CardNumber == cardNumber)
                .Select(b => b.EmployeeName)
                .FirstOrDefault();

            Name = employeeName;
            CardNumber = cardNumber;

            if (!ModelState.IsValid || _context.Ticket == null || Ticket == null)
              {
                  return Page();
              };

            Ticket.CreatedAT = DateTime.Now;

            var receiver = "";
            var subject = this.Ticket.Subject + " " + this.Name;
            var message = "S-a creat o solicitare din parea lui " + this.Name + ", a cerut: " + this.Ticket.Subject
                + System.Environment.NewLine + "Solicitarea s-a creat la data : " + DateTime.Now;

            await _emailSender.SendEmailAsync(receiver, subject, message);

            _context.Ticket.Add(Ticket);
            await _context.SaveChangesAsync();

            return RedirectToPage("/ThankYou");
        }
    }
}

Ticket_App/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Manage.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ticket_App.Models;

namespace Ticket_App.Pages
{
    public class IndexModel : PageModel
    {
        private readonly Ticket_App.Data.ApplicationDbContext _context;

        public IndexModel(Ticket_App.Data.ApplicationDbContext context)
        {
            _context = context;
            
        }

        public void OnGet()
        {

        }
        
        public IActionResult OnPostSubmit(Employee employee)
        {

            int cardNumberCheck = 0;

            cardNumberCheck = _context.Employee
                .Where(a => a.CardNumber == employee.CardNumber)
                .Select(b => b.EmployeeId)
                .FirstOrDefault();

            

            if (employee.CardNumber == null)
            {
                ModelState.AddModelError("InvalidCardNumber", "Va rugam introduceti seria cardului");
                return Page();
            }
            else if (cardNumberCheck == 0)
            {
                ModelState.AddModelError("InvalidCardNumber", "Nu exista cardul cu seria asta");
                return Page();
            }
            else
            {
                return RedirectToPage("/Create", new {cardNumber = employee.CardNumber});
            }
          
        }
        
    }
}

Ticket_App/Pages/ThankYou.cshtml.cs
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ticket_App.Pages
{
    public class ThankYouModel : PageModel
    {
        public void OnGet()
        {
            Response.Headers.Add("Refresh", "5;/Index");
        }
    }
}

Ticket_App/Pages/Create.cshtml
@page
@model Ticket_App.Pages.Shared.Tickets.CreateModel

@{
    ViewData["Title"] = "Crează";
}
<div class="text-center">
    <h1>Bună ziua <strong style="font-weight:bold">@Model.Name</strong></h1>
    <br />
    <h3>Deschide o solicitare nouă alegând unul din subiectele de mai jos:</h3>
    <hr />
    <br />
    <form method="post">

        <div class="container-fluid">

            <div class="row">

                <div class="col">
                    @for (var topicIndex = (Model.Topics.Count() / 2); topicIndex < Model.Topics.Count(); topicIndex++)
                    {
                        string imgpath = "/Pictures/click-icon.jpg";
                        @if (@Model.Topics[topicIndex].ImageName != "")
                        {
                            imgpath = "/Pictures/" + @Model.Topics[topicIndex].ImageName.ToString();
                        }

                        <div class="radiobtn">
                            <input id="@Model.Topics[topicIndex].TicketTopicID" asp-for="Ticket.Subject" type="radio" value="@Model.Topics[topicIndex].TicketTopicName" />

                            <label for="@Model.Topics[topicIndex].TicketTopicID" asp-for="Ticket.Subject"> <img src="@imgpath" class="img-fluid" id="imgButton" /> @Model.Topics[topicIndex].TicketTopicName </label>

                        </div>
                        <br />
                        <br />

                    }
                </div>

                <div class="col">
                    @for (var topicIndex = 0; topicIndex < Model.Topics.Count() / 2; topicIndex++)
                    {
                        string imgpath = "/Pictures/click-icon.jpg";
                        @if (@Model.Topics[topicIndex].ImageName != "")
                        {
                            imgpath = "/Pictures/" + @Model.Topics[topicIndex].ImageName.ToString();
                        }

                        <div class="radiobtn">
                            <input id="@Model.Topics[topicIndex].TicketTopicID" asp-for="Ticket.Subject" type="radio" value="@Model.Topics[topicIndex].TicketTopicName" />
                            <label for="@Model.Topics[topicIndex].TicketTopicID" asp-for="Ticket.Subject"> <img src="@imgpath" class="img-fluid" id="imgButton" /> @Model.Topics[topicIndex].TicketTopicName </label>
                        </div>
                        <br />
                        <br />
                    }
                </div>

            </div>
        </div>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group" hidden>
            <input asp-for="Ticket.CardNumber" class="form-control" value="@Model.CardNumber" />
            <span asp-validation-for="Ticket.CardNumber" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <input asp-for="Ticket.EmployeeName" class="form-control" value="@Model.Name" />
            <span asp-validation-for="Ticket.CardNumber" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <input asp-for="Ticket.Subject" class="form-control" value="" />
            <span asp-validation-for="Ticket.Subject" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" style="font-size: xx-large" value="Crează solicitare" class="btn btn-primary" />
        </div>

    </form>
    <hr />
    <br />
    <div>
        <button type="button" class="btn btn-warning"> <a style="color:white;font-size: xx-large; text-decoration:none" asp-page="/Index">Anulează</a> </button>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>

        (function () {

            const idleDurationSecs = 30;    // X number of seconds
            const redirectUrl = '/Index';  // Redirect idle users to this URL
            let idleTimeout; // variable to hold the timeout, do not modify

            const resetIdleTimeout = function () {

                // Clears the existing timeout
                if (idleTimeout) clearTimeout(idleTimeout);

                // Set a new idle timeout to load the redirectUrl after idleDurationSecs
                idleTimeout = setTimeout(() => location.href = redirectUrl, idleDurationSecs * 1000);
            };

            // Init on page load
            resetIdleTimeout();

            // Reset the idle timeout on any of the events listed below
            ['click', 'touchstart'].forEach(evt =>
                document.addEventListener(evt, resetIdleTimeout, false)
            );

        })();
    </script>
}

Ticket_App/Pages/Index.cshtml
@page
@using Ticket_App.Models

@model Ticket_App.Pages.IndexModel
@{
    ViewData["Title"] = "Acasă";
}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<div class="text-center" style="border: 1px solid black; background-color: #F3F3F3;">
    <br />
    <img src="Pictures/banner.png" class="img-fluid" id="img-banner"/>
    <br />
    <br />
    <p style="font-size:35px;"> Pentru a simplifica cererile de asistență și a vă servi mai bine, <br /> utilizăm un sistem de tichete de asistență Support HR. </>
        <br />
    <p style="font-size:40px; font-weight:bold"> Scanați cartela pe cititor pentru a începe:</p>
    <img src="~/Pictures/card_scan.png" class="img-fluid" id="img-cardScan"/>
    <form method="post">    
        <input type="text" class="txtCardId" id="txtCardId" name="CardNumber" autofocus onfocus="this.select()" autocomplete="off" />
    <br />
    <br />
    <div class="form-group">
        <input type="submit" asp-page-handler="Submit" style="font-size: xx-large" value="Crează solicitare" class="btn btn-primary" hidden />
    </div>
    <p align="center" style="color:red">@Html.ValidationMessage("InvalidCardNumber")</p>
    </form>
</div>



@section Scripts {

    <script>
        (function () {
            
            const idleDurationSecs = 30;    // X number of seconds
            const redirectUrl = '/Index';  // Redirect idle users to this URL
            let idleTimeout; // variable to hold the timeout, do not modify

            const resetIdleTimeout = function () {

                // Clears the existing timeout
                if (idleTimeout) clearTimeout(idleTimeout);

                // Set a new idle timeout to load the redirectUrl after idleDurationSecs
                idleTimeout = setTimeout(() => location.href = redirectUrl, idleDurationSecs * 1000);
            };

            // Init on page load
            resetIdleTimeout();

            // Reset the idle timeout on any of the events listed below
            ['click', 'touchstart'].forEach(evt =>
                document.addEventListener(evt, resetIdleTimeout, false)
            );


        })();
        
    </script>

    <script >
        $(function () {
            $(".txtCardId").bind("focusout", function (e) {
                if (!isValidString($(this).val())) {
                    e.preventDefault();
                    $(this).focus();
                }
            });
        });

        // Function to check whether the
        // string is "geeks" or not
        function isValidString(s) {
            return s != "" && s == "";
        }
    </script>

    <script>
        $(document).ready(function () {
            history.pushState(null, document.title, location.href);
        });
    </script>
}

Ticket_App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ticket_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ticket_App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <img src="/Pictures/Carmistim-HR-Final-lung.png" width="150" height="27"/>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ticket_App/Pages/ThankYou.cshtml
@page
@model Ticket_App.Pages.ThankYouModel
@{
    ViewData["Title"] = "Mulțumim";
}

<div class="text-center">
    <br />
    <img src="Pictures/banner.png" width="1140" height="360" />
    <br />
    <br />
    <p style="font-size:55px"> Mulțumim pentru cererea creată. <br /> Vom încerca să rezolvăm cerera in cel mai scurt timp posibil. </p>
    <br />

</div>